### ISSUE TITLE
How to hide this plugin in Status bar?

### ISSUE THREAD

**Issue by LoneFireBlossom** [erincayaz/obsidian-colored-text#26]
**Is your feature request related to a problem? Please describe.**
I usually use Obsidian in split screen, so status bar is short.
So I don't want to put too much things in status bar, otherwise it will be like that:

![CleanShot 2023-09-22 at 13 21 05](https://github.com/erincayaz/obsidian-colored-text/assets/50087596/dcff4f4d-27d1-4013-8c5e-8f887fa17f45)

**Describe the solution you'd like**
I only use hotkeys to use this plugin, so I think that adding an option to let this plugin doesn't show in status bar is ok.

**Additional context**
Thanks for your plugin ^_^

**Comment by erincayaz** [comment]
Hi, an option to hide the color bar seems logical. I will implement it in the next release. Until then, maybe you can decrease the number of color cells using the settings.

**Comment by erincayaz** [comment]
Hi, I released a new version that covers this issue #27. Hope it is suitable for your use case, let me know! Have a nice day.

**Comment by LoneFireBlossom** [comment]
thanks!
