### ISSUE TITLE
Modal highlight control, like in most pdf readers

### ISSUE THREAD

**Issue by notuntoward** [erincayaz/obsidian-colored-text#28]
I like the function of this plugin, but I'm noticing that each highlight takes more clicks or hotkeys than I am used to on other tools, like Abdobe, pdfXchangeEditor, Drawboard, OneNote,...

In those tools, you click a button on a color picking palette once, and then you are in highlighting mode: anything you select with a mouse or a keyboard (implementations vary) gets highlighted in whatever color is currently active on the palette, which is open as long as you're in highlighting mode.  If you select already highlighted text, and then click a delete button (various implementations) then that highlighting is removed.  But you stay in highlighting mode until you turn it off.

### Here's OneNote's palette:

![image](https://github.com/erincayaz/obsidian-colored-text/assets/3851891/ee3af92d-aefa-459d-85da-80a94e1b4a9b)

You just click a pen at the top, and then you can highlight with no further clicking required, until you want to delete a highlight, want to change colors (click a pen), or want to stop highlighting, in which case you click it off.

**Comment by erincayaz** [comment]
Actually, my first intention was to implement the plugin this way. However, I don't know if it is possible to do that using Obsidian's API. I will investigate this matter and keep you updated. Thanks for the issue by the way!

**Comment by notuntoward** [comment]
Glad to hear it.  It seems to me that a modal highlighter would be possible in Obsidian.  One piece of evidence is how the [obsidian editing toolbar](https://github.com/PKM-er/obsidian-editing-toolbar/commits/master) does highlight _erasing_.  Once you've clicked the plugin's "clear text formatting" icon circled in red below:
<img width="526" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/18eb5f32-b552-4f21-acdc-742fa6715bbc">


then you're in "erase mode."  In this state, highlights and other formatting are removed from any text you drag the mouse over.  You don't need to repeatedly click this icon, as the plugin stays in erase mode until you click it off.

It seems like _making_ highlighting could work the same way.  But oddly, this plugin doesn't do that either.

**Comment by erincayaz** [comment]
Thanks for the point in direction. I investigated the code and tried to implement it. And it seems doable so I plan to implement this in the next release.

**Comment by erincayaz** [comment]
Added the highlight mode with the new release:

![output](https://github.com/erincayaz/obsidian-colored-text/assets/45971992/60529055-c3f3-46c2-861c-431f3f2a0288)

**Comment by notuntoward** [comment]
Thanks.  This works quite well, and I think this change makes it the best Obsidian plugin of its kind.

If you're looking for more feedback, my main request would be to improve it for light mode screens.  Here some suggestions:

- Pick a highlight mode icon color that's visible on a light screen.  The first screenshot below shows the icon in the ON state; the second in the OFF state.  I can't see the difference.
- the highlight mode icon popup says "Hightlight Mode" but I think most people wouldn't consider what it currently does to be "highlighting."  "colored text" would be more accurate.
- I'm finding that highlights -- usual meaning for this word -- are more visible on light screens than is colored text.  I'd suggest adding a "highlight" option

<img width="118" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/b86c4ce9-0ce9-4bd0-aa9a-1f2540f1c430">
<img width="98" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/1b01935c-b102-45ab-a718-4f7174e1a52c">
