### ISSUE TITLE
hide html as soon as highlighting is completed

### ISSUE THREAD

**Issue by notuntoward** [erincayaz/obsidian-colored-text#29]
When I've selected some text to highlight, and then right click and select "Color Text" on the menu, the text is colored immediately, as expected:

<img width="416" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/9aa1bd89-3eb6-4108-afc6-b96ea0bffbf2">

However, if I select the same text, and try to color it by running `Colored Text: Color Text`, either with a hotkey or with the command palette, then I see the unrendered html that will color the text only after I click off of it:

<img width="411" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/4598bd8d-e343-4ab5-973a-e20dc5178e29">

I'd like it if the behavior for `Colored Text: Color Text` was the same as when the menu is used: immediately hide the html and color the text.

**Comment by erincayaz** [comment]
Hi. First of all thanks for trying out the plugin! The reason for this behavior was to protect original behavior of the Obsidian itself. In the Obsidian when you format the text (bold, italic) using keyboard shortcuts, the cursor will stay inside the asterisks. Because of that @rl16432 suggested it would be logical to keep consistent with Obsidian's original behavior #10. However it may be logical to add a setting and let users choose their way of using the plugin.

**Comment by notuntoward** [comment]
Yes, I understand the consistency goal, but in the case of bolding or italicizing, the raw markdown is only a few small characters -- so inobtrusive that I didn't even notice them until you pointed them out.  The html for highlighting is a quite a different story.

I would guess that this is why the [highlightr plugin](https://github.com/chetachiezikeuzor/Highlightr-Plugin) doesn't display it.  Yet it is consistent with standard Obsidian; its html does display when you move the cursor on top of it.  It's just that, at the end of its highlighting operation, it moves the cursor off of it.

**Comment by erincayaz** [comment]
I believe that hiding the HTML would provide a better user experience. I'll include this change in the next release and will notify you once it's added.

**Comment by erincayaz** [comment]
Hi, sorry for the late update. Right now coloring works like this with the new release.
