### ISSUE TITLE
HTML Font tag is deprecated, replace with Span tag?

### ISSUE THREAD

**Issue by krausekai** [erincayaz/obsidian-colored-text#3]
For https://github.com/erincayaz/obsidian-colored-text/blob/be050f389a944346443127332661f7df9c25f45a/src/main.ts#L36

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font

**Comment by krausekai** [comment]
https://github.com/erincayaz/obsidian-colored-text/blob/main/src/main.ts#LL43C3-L43C3

Thanks for looking into it. However, it seems the ending `</font>` tag wasn't updated 😅

**Comment by erincayaz** [comment]
Oops, didn't know it could work like that 😄. Replaced it.
