### ISSUE TITLE
enable hotkey instead of right-clicking

### ISSUE THREAD

**Issue by scottsus** [erincayaz/obsidian-colored-text#30]
Currently, the way to apply the selected color is to highlight the selected text, right click, and press _color text_.
<img width="709" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/88414565/c344e44d-a54c-4bab-993a-164d66b57052">
This is fine, but it's not the most efficient solution for those who want to stick to their keyboards.

It would be amazing if we could set a custom hotkey for this behavior. We could highlight the text using arrow keys, then apply the custom hotkey to apply the chosen color. For example in Notion, this behavior exists with the hotkey CMD+SHIFT+H (for Mac users).

Thanks in advance!

**Comment by erincayaz** [comment]
Hi, first of all, thanks for trying out the plugin and creating an issue. Actually, there are hotkeys defined for the plugin. You can find them in the settings at the hotkeys tab, there are no default hotkeys defined but you can define your own. 

![Screenshot 2023-11-16 at 21 37 57](https://github.com/erincayaz/obsidian-colored-text/assets/45971992/ae91afba-0b5f-465b-8cae-37c3e3638ffd)

But seeing your issue made me think that maybe I should improve the contents of the README 😅.

**Comment by scottsus** [comment]
My bad, new to Obsidian, thanks for the response, appreciate it!
