### ISSUE TITLE
This plugin could take broader customization scope than just coloring text

### ISSUE THREAD

**Issue by nikelborm** [erincayaz/obsidian-colored-text#31]
Today I accidentally found that it does not only support coloring text but also allows to insert many more inline styles.

May be it's better for this plugin to take broader scope of customization? As an idea maybe make it allow in settings to set user's own css classes and then apply them to some spans that have `class` attribute

**Comment by nikelborm** [comment]
![Screenshot from 2024-01-05 09-38-52](https://github.com/erincayaz/obsidian-colored-text/assets/29357907/b3f72871-4388-4419-a5d2-51a88e8c86cb)
![Screenshot from 2024-01-05 09-39-03](https://github.com/erincayaz/obsidian-colored-text/assets/29357907/758129a9-c086-41a8-9c5a-e9092fac4ff1)

In this case you can do such amazing customizations very easy and reusable with css classes

**Comment by erincayaz** [comment]
Hi, allowing users to add their custom css in settings is actually a really cool idea. I would want to do this together, you can add me from discord `muhittin852` and we can discuss the next steps.
