### ISSUE TITLE
Improved light mode

### ISSUE THREAD

**Issue by notuntoward** [erincayaz/obsidian-colored-text#33]
Thanks for the [great usability improvements](https://github.com/erincayaz/obsidian-colored-text/issues/28).

If you're looking for more feedback, my main request would be to improve the plugin for light mode screens. Here some suggestions:

- Pick a highlight mode icon color that's visible on a light screen. One screenshot below is a zoom of the icon in the ON state; the ohter in the OFF state. At normal screen scaling, I can't see the difference.
- the highlight mode icon popup says "Hightlight Mode" but I think most people wouldn't consider what it currently does to be "highlighting." "colored text" would be more accurate.
- I'm finding that highlights -- usual meaning for this word -- are more visible on light screens than is colored text. I'd suggest adding a "highlight" option

<img width="268" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/14e53ef5-5b36-46bc-922b-0d1ba5f0994f">
<img width="224" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/3851891/66644906-04f2-4927-b991-a2f34418c14b">

**Comment by erincayaz** [comment]
I actually realized this recently. I didn't keep light mode in mind while developing so the colors of these features are bad for light mode. I am planning to make color selections dynamic depending on the theme, thanks for the issue.

**Comment by erincayaz** [comment]
Hello fixed the issue with the new release:

- Highlight color is now changes according to theme:
![Screenshot 2024-06-09 at 14 03 23](https://github.com/erincayaz/obsidian-colored-text/assets/45971992/22c47478-ac6e-46d9-af37-2875a2efe003)
![Screenshot 2024-06-09 at 14 04 06](https://github.com/erincayaz/obsidian-colored-text/assets/45971992/43877613-1f06-4318-8ae9-ab95671c15db)
- Changed the button's name to colored text button
- Frame of the current color now changes according to theme as well

---
Right now I am not planning to add Highlight option to the plugin but when I finish the things I want to do, I will see if I can implement it without breaking simplicity of the plugin. Again thanks for the issue!

**Comment by notuntoward** [comment]
Thanks, with the icon shading change, light mode usability is greatly improved.  Still hoping for a highlighter, whenever you find the time.
