### ISSUE TITLE
Can't toggle color unless text is selected

### ISSUE THREAD

**Issue by Syntrice** [erincayaz/obsidian-colored-text#37]
**Describe the bug**
Since a recent update, executing the toggle color command or hotkey does not insert the html code for color unless text is selected (in short, it can only be used to highlight text)

**To Reproduce**
1. Activate carat on blank line
2. Execute color text command

**Expected behavior**
A html code block should be inserted to set the color

**OS**
Windows 11

**Comment by erincayaz** [comment]
Hello, yes this is a bug. I will let you know when it is fixed.

Thanks for the issue.

**Comment by erincayaz** [comment]
Hi, fixed the issue with the new release
