### ISSUE TITLE
Update 1.1.0 Incorrectly Labeled

### ISSUE THREAD

**Issue by Afurai** [erincayaz/obsidian-colored-text#42]
**Describe the bug**
When checking for updates through Obsidian's community plugins tab I noticed that Colored Text says it needs to update. You press update and the plugin "successfully installs" but still appears to be stuck on 1.0.0. I had a look through the manifest.json file and noticed that the version number on the newly downloaded "Version 1.1.0" file contains "version": "1.0.0", instead of the expected 1.1.0

**To Reproduce**
1. Have 1.0.0 version of the Colored Text plugin
2. Go to the community plugins tab in Obsidian
3. Current plugins -> Check for updates
4. See Colored Text has an update -> press update
5. You can repeat steps 3 and 4 indefinitely and the program will never update to 1.1.0

**Expected behavior**
The program is supposed to say "Successfully installed Colored Text" and the version number of Colored Text in the community plugins tab will now read "Version: 1.1.0" instead of the currently present "Version: 1.0.0"

**Screenshots**
Here is the ![image](https://github.com/erincayaz/obsidian-colored-text/assets/149650378/71ec4773-87b9-42bd-9e38-da3a41a78e0e) of the newly downloaded "version 1.1.0" manifest.json file

**OS**
W10 22H2; Build 19045.3803

**Additional context**
I think this issue is due to the wrong files being uploaded ;)

**Comment by erincayaz** [comment]
Hi, thanks for the issue. Fixed with the new release
