### ISSUE TITLE
[BUG] It updates endlessly on OB console

### ISSUE THREAD

**Issue by ianTevesAcc** [erincayaz/obsidian-colored-text#44]
**Describe the bug**
Currently the terminal is continuously printing on the Obsidian console. At this moment it's not affecting my program negatively. I'm just worried that it might endlessly increase (when left overnight) and cause a crash or something.

**To reproduce**
1. activate and install OB colored text plugin.
2. restart obsidian.
3. open terminal console and clear using clear() command.

**Expected behavior**
A clear console to appear and stay like that.

**Actual Result**
obsidian console updates coming from the OB colored text plugin - running endlessly while the plugin is active.

**Screenshots**
![image](https://github.com/erincayaz/obsidian-colored-text/assets/105651670/51e7dcd8-919d-4ef4-b7e6-aa02513ae43c)
![image](https://github.com/erincayaz/obsidian-colored-text/assets/105651670/c7782b8f-de40-47fd-bc69-e5d0dbbc3bfb)

**OS**
Windows 11

**Comment by erincayaz** [comment]
Hi, thanks for the issue. Fixed with the new release

**Comment by ianTevesAcc** [comment]
Thank you for your work! o7
