### ISSUE TITLE
Enhancement Bold Italics

### ISSUE THREAD

**Issue by MK-Basha** [erincayaz/obsidian-colored-text#7]
This plugin solves the basic need of highlighting. Would suggest adding "BOLD" , "Italic" and "Strikeout" feature additional. This would make the plugin usage more productive.

**Comment by erincayaz** [comment]
As far as I know Obsidian already has this feature. Ctrl + B makes the selected text bold, and vice versa, you can find them in hotkeys.

**Comment by MK-Basha** [comment]
Thanks I found them.
