### ISSUE TITLE
Settings > Options has no way back to Settings

### ISSUE THREAD

**Issue by zburq** [erincayaz/obsidian-colored-text#9]
From settings, if I select Options (Number of color cells, default = 5), I cannot go back to settings. I have to go back to Community plugins and find Colored Text and start over.

**Comment by erincayaz** [comment]
Could you please provide more information about the bug you encountered? Additionally, it would be helpful to know which operating system you are using (Windows or Mac) so that I can better understand the context of the issue.

**Comment by zburq** [comment]
I'm using Mac OS 13. 
If I search and select Colored Text from my installed plugins, I get this: 
<img width="774" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/6443451/ac7d64b6-ba07-4696-b737-a9912c183121">
Next, if I click on Options, I get this: 
<img width="818" alt="image" src="https://github.com/erincayaz/obsidian-colored-text/assets/6443451/6940fb8d-24cb-408d-a3d5-932ec631fc0e">
From here, I can't go back to the main page to set Hotkeys etc.  I have to go back to Community Plugins and start over.
